# -*- coding: utf-8 -*-
"""ITC Hotels Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThhAYAM08qG1WzEpW6puno_662XAdr8w

# **ITC Hotels Project**

# **Starting the Project**
"""

#Importing the required libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the data file.
#from google.colab import drive
#drive.mount('/content/drive')
df_itc = pd.read_csv(r"C:\Users\dhruv\OneDrive\Documents\Dhruv DA Folder\Python\ITC_Hotels.csv",sep= ',')

"""# **Basic EDA**

1. Show the first 10 rows of the dataset.
"""

print(df_itc.head(10))

"""2. How many rows and columns does the dataset have?"""

print('Number of records:',df_itc.shape[0])
print('Number of columns:',df_itc.shape[1])

"""3. Display all column names and their data types."""

print('List of Column Names:',df_itc.columns.tolist())
print()
print(df_itc.dtypes)

"""4. Show the statistical summary of all numeric columns."""

print('Statistical summary of numeric columns')
print(df_itc.describe())
print()

"""5. How many duplicate rows exist? Remove them and confirm the new shape."""

print("Number of Duplicate Records:",df_itc.duplicated().sum())
print()
if df_itc.duplicated().sum() > 0:
  df_itc = df_itc.drop_duplicates
  print("Shape of Dataset:",df.shape())

"""6. Clean the data properly and format the data with the proper datatypes."""

#Formatting the data with the proper datatypes
df_itc['Checkin_Date'] = pd.to_datetime(df_itc['Checkin_Date'])
df_itc['Checkout_Date'] = pd.to_datetime(df_itc['Checkout_Date'])
print('New datatypes',df_itc.dtypes)
print()

#Checking for null-values
print('Null values for each columns')
print(df_itc.isnull().sum())
print()

#Stripping the whitespaces in 'object' dtypes
for col in df_itc.select_dtypes(include='object').columns:
    df_itc[col] = df_itc[col].str.strip()


print('Data Cleaning: Completed')

"""# **Feature Engineering**

1. Create a Revenue_Per_Night column: Net Revenue divided by Nights Stayed.
"""

df_itc['Revenue_Per_Night'] = df_itc['Net_Revenue']/df_itc['Nights_Stayed']

"""2. Create a Discount_Pct column: Discount as a percentage of Gross Revenue."""

df_itc['Discount_Pct'] = (df_itc['Discount']/df_itc['Gross_Revenue'])*100

"""3. Create a Revenue_Per_Guest column: Net Revenue divided by Guests."""

df_itc['Revenue_Per_Guest'] = df_itc['Net_Revenue']/df_itc['Guests']

"""4. Create a High_Rating flag - 1 where Customer Rating >= 4.5, else 0."""

df_itc["High_Rating"] = (df_itc["Customer_Rating"] >= 4.5).astype(np.int32)

"""5. Rename Covid_Impact_Level to Covid_Impact. Reorder so Booking_ID,Hotel_Name, City appear first."""

df_itc.rename(columns={'Covid_Impact_Level':'Covid_Impact'},inplace = True)

df_itc[['Booking_ID','Hotel_Name','Hotel_Category','City','State','Country','Checkin_Date','Checkout_Date','Month','Quarter','Year','Room_Type','Guests','Nights_Stayed','Room_Rate','Extra_Charges','Discount','Gross_Revenue','Net_Revenue','GST_Amount','Total_With_GST','Booking_Channel','Customer_Type','Payment_Mode','Occupancy_Status','Customer_Rating','Feedback_Status','Covid_Impact']]
print('New Column Order')
print(df_itc.columns)

"""# **Basic Business Queries**

1. List all bookings where Nights Stayed is greater than 3.
"""

print('Total Bookings greater than 3:',df_itc[df_itc['Nights_Stayed'] > 3].shape[0])
print()
df1 = df_itc[df_itc['Nights_Stayed'] > 3]
df1

"""2. List all bookings made in the city of Goa."""

print('Total Bookings Made in Goa:',df_itc[df_itc['City'] == 'Goa'].shape[0])
print()
df2 = df_itc[df_itc['City'] == 'Goa']
df2

"""3. Show bookings where Booking Channel is Walk-in and Nights Stayed > 2."""

print('Total Bookings where Booking Channel is Walk-in and Nights Stayed > 2:',df_itc[(df_itc['Booking_Channel']=='Walk-in') & (df_itc['Nights_Stayed']>2)].shape[0])
print()
df3 = df_itc[(df_itc['Booking_Channel']=='Walk-in') & (df_itc['Nights_Stayed']>2)]
df3

"""4. Show bookings where Customer Rating is 5.0 or Net Revenue is above 100000."""

print('Total Bookings where Customer rating is 5.0 or revenue >100000:',df_itc[(df_itc['Customer_Rating'] == 5.0) | (df_itc['Net_Revenue'] > 100000)].shape[0])
print()
df4 = df_itc[(df_itc['Customer_Rating'] == 5.0) | (df_itc['Net_Revenue'] > 100000)]
df4

"""5. Use query() to find all Luxury hotel bookings with Customer Rating above 4.0."""

print('Total Luxury and above 4.0 Bookings:',df_itc.query("(Hotel_Category == 'Luxury' ) & (Customer_Rating > 4.0)").shape[0] )
print()
df5 = df_itc.query("(Hotel_Category == 'Luxury' ) & (Customer_Rating > 4.0)")
df5

"""6. Show all Presidential Suite bookings sorted by Net Revenue, highest first."""

print('Total President Suite Bookings:',df_itc[df_itc['Room_Type']=='Presidential Suite'].shape[0])
print()
df6 = df_itc[df_itc['Room_Type']=='Presidential Suite']
df6.sort_values(by='Net_Revenue',ascending=False)

"""7. What is the total Net Revenue across all bookings?"""

print('Total Net Revenue:',df_itc['Net_Revenue'].sum())

"""8. What is the maximum and minimum Customer Rating?"""

df_itc['Customer_Rating'].agg(['min','max'])

"""9. Show all bookings with zero discount applied."""

print('Total Bookings with 0 discounts:',df_itc[df_itc['Discount'] == 0].shape[0])
print()
df9 = df_itc[df_itc['Discount'] == 0]
df9

"""# **NumPy Analysis**

1. Descriptive statistics on Net Revenue using NumPy.
"""

df_itc['Net_Revenue'].agg([
    'min','max','mean','median','std','var','sum','count'
])

"""2. Use np.unique() on Nights Stayed, Year, and Quarter."""

a =np.unique(df_itc['Nights_Stayed'])
print('Unique Nights Stayed:',a)
print()
b =np.unique(df_itc['Year'])
print('Unique Years:',b)
print()
c =np.unique(df_itc['Quarter'])
print('Unique Quarters:',c)

"""3. Boolean mask - count bookings where Discount > 3000. Show as percentage."""

boolean_mask = df_itc[df_itc['Discount'] > 3000].shape[0]/df_itc.shape[0]*100
print('Bookings percentage where Discount > 3000:',boolean_mask,'%')

"""4. 2D matrix from Net Revenue and GST Amount. np.sum on axis=0 and axis=1."""

arr = np.array(df_itc[['Net_Revenue','GST_Amount']])
print('Total Net Revenue and GST respectively:',np.sum(arr,axis=0))
print()
print('Sum of Revenue and GST:',np.sum(arr,axis=1))

"""5. Quarterly Net Revenue - np.diff() and np.cumsum()."""

print('Quarterly Net Revenue Difference:',np.diff(df_itc.groupby('Quarter')['Net_Revenue'].sum()))
print()
print('Quarterly Net Revenue Cumulative Sum:',np.cumsum(df_itc.groupby('Quarter')['Net_Revenue'].sum()))

"""6. Compare np.mean() and np.median(). State if distribution is skewed.

Yes, the distribution is positively skewed as mean(49,716) is greater than the median(42,477).
"""

print('Mean:',np.mean(df_itc['Net_Revenue']))
print('Median:',np.median(df_itc['Net_Revenue']))

"""# **Advanced Pandas Queries**

1. Total Net Revenue per Hotel Category. Sort highest to lowest.
"""

total_net_revenue = df_itc.groupby('Hotel_Category')['Net_Revenue'].sum()
total_net_revenue.sort_values(ascending=False)

"""2. Average Customer Rating per Room Type. Sort best to worst."""

avg_cust_rating = df_itc.groupby('Room_Type')['Customer_Rating'].mean()
avg_cust_rating.sort_values(ascending=False)

"""3. Top 5 cities by total Net Revenue."""

top_5_cities = df_itc.groupby('City')['Net_Revenue'].sum().rank(method='dense')
top_5_cities.sort_values(ascending=False).head(5)

"""4. Average Net Revenue per booking for each Booking Channel. Sort descending."""

avg_revenue_per_booking = df_itc.groupby('Booking_Channel')['Net_Revenue'].mean()
avg_revenue_per_booking.sort_values(ascending=False)

"""5. Total Gross Revenue per Month."""

total_gross_revenue = df_itc.groupby('Month')['Gross_Revenue'].sum()
total_gross_revenue.sort_values()

"""6. Multi-metric aggregation for Hotel Category in one agg() call."""

multi_metric_agg = df_itc.groupby("Hotel_Category")["Net_Revenue"].agg(
    Total_Revenue   = "sum",
    Avg_Revenue     = "mean",
    Highest_Booking = "max",
    Lowest_Booking  = "min",
    Booking_Count   = "count"
)
multi_metric_agg.sort_values(by="Total_Revenue",ascending=False)

"""7. Average Customer Rating and booking count per Hotel Name."""

avg_cust_rating = df_itc.groupby('Hotel_Name')['Customer_Rating'].mean().sort_values(ascending=False)
print('Average Customer Rating per Hotel')
print(avg_cust_rating.sort_values(ascending=False))
print()

avg_booking_count = df_itc.groupby('Hotel_Name')['Booking_ID'].count().sort_values(ascending=False)
print('Average Booking Count per Hotel')
avg_booking_count.sort_values(ascending=False)

"""8. Total Net Revenue grouped by Year and Quarter."""

total_net_revenue_grouped = df_itc.groupby(['Year','Quarter'])['Net_Revenue'].sum()
print('Total Net Revenue for FY21')
total_net_revenue_grouped

"""9. Keep only Hotel Categories whose average Net Revenue is above the overall average."""

above_avg = df_itc.groupby('Hotel_Category').filter(lambda x :x['Net_Revenue'].mean() > df_itc['Net_Revenue'].mean())
above_avg.groupby('Hotel_Category')['Net_Revenue'].mean().sort_values(ascending=False)

"""10. Average Discount_Pct per Customer Type. Sort descending."""

avg_discount = df_itc.groupby('Customer_Type')['Discount'].mean()
avg_discount.sort_values(ascending=False)

"""11. Total revenue, avg revenue, and booking count per Payment Mode."""

total_revenue_per_payment_mode = df_itc.groupby('Payment_Mode')['Net_Revenue'].agg(
    Total_Revenue   = "sum",
    Avg_Revenue     = "mean",
    Booking_Count   = "count"
)
total_revenue_per_payment_mode.sort_values(by="Total_Revenue",ascending=False)

"""12. Rank all cities by average Net Revenue using rank(method='dense')."""

city_rank = df_itc.groupby('City')['Net_Revenue'].mean().rank(method='dense')
city_rank.sort_values(ascending=False)

"""13. All Negative feedback bookings. Count per Hotel Name."""

neg_feedback = df_itc[df_itc['Feedback_Status']=='Negative']
neg_feedback.groupby('Hotel_Name')['Booking_ID'].count().sort_values(ascending=False)

"""# **Business Insights**

1. Which hotel category should be prioritised for expansion?

Luxury beats all the other categories on total revenue, average revenue and total number of bookings. Capital expenditure on Luxury hotel category yields the best ROI.
"""

expansion_priority = df_itc.groupby('Hotel_Category')['Net_Revenue'].agg(
    Total_Revenue = 'sum',
    Avg_Revenue = 'mean',
    Count_of_Bookings = 'count'
)
expansion_priority.sort_values(by =['Total_Revenue','Avg_Revenue','Count_of_Bookings'],ascending=[False,False,False])

"""2. Which booking channels should get more marketing investment?

Website and Corporate channels should get more marketing investment as they have highest average revenue and are direct channels with untapped volumes and zero commission leakage.
"""

marketing_investment = df_itc.groupby('Booking_Channel')['Net_Revenue'].agg(
    Total_Revenue = 'sum',
    Avg_Revenue = 'mean',
    Count_of_Bookings = 'count'
)
marketing_investment.sort_values(by =['Total_Revenue','Avg_Revenue','Count_of_Bookings'],ascending=[False,False,False])

"""3. How much does COVID impact level affect per-booking revenue?

High covid impact period crushed revenue via government set occupancy caps and frozen corporate travels.
"""

covid_impact = df_itc.groupby('Covid_Impact')['Net_Revenue'].agg(
    Total_Revenue = 'sum',
    Avg_Revenue = 'mean',
    Count_of_Bookings = 'count'
)
covid_impact

"""4. Use groupby filter() to isolate high-performing hotel categories."""

high_performing_hotels = df_itc.groupby('Hotel_Category').filter(lambda x: x['Net_Revenue'].mean() > df_itc['Net_Revenue'].mean())
hotel_performance_metrics = high_performing_hotels.groupby('Hotel_Name')['Net_Revenue'].agg(
    Total_Revenue = 'sum',
    Avg_Revenue = 'mean',
    Count_of_Bookings = 'count'
)
hotel_performance_metrics.sort_values(by =['Total_Revenue','Avg_Revenue','Count_of_Bookings'],ascending=[False,False,False])

"""5. Does giving a higher discount lead to a better rating?

Discount and Customer Rating has near zero correlation.
Discount does not buy satisfaction. Service quality, room cleanliness, and staff behaviour drive ratings and not price cuts.
"""

corr_dis_rating = df_itc["Discount"].corr(df_itc["Customer_Rating"])
print('Corelation between discount and customer rating:',round(corr_dis_rating,3))

"""6. What does std() and var() on Net Revenue tell about booking value?

A high standard deviation signals extreme booking value differences. ITC Hotels serves both modest 1-night stays and multi-night presidential bookings which created a high standard deviation.
"""

print('Standard Variance of Net Revenue:',round(df_itc['Net_Revenue'].std(),2))
print()
print('Variance of Net Revenue:',round(df_itc['Net_Revenue'].var(),2))

"""7. Compare avg Net Revenue - VIP vs Corporate customers.

Corporate customer has higher average net revenue compared to vip customers due to their higher volumes and average room rates
"""

vip_revenue = df_itc[df_itc['Customer_Type'] == 'VIP']['Net_Revenue'].mean()
corporate_revenue = df_itc[df_itc['Customer_Type'] == 'Corporate']['Net_Revenue'].mean()
print('Average Net Revenue for VIP:',round(vip_revenue,2))
print('Average Net Revenue for Corporate:',round(corporate_revenue,2))
print()
diff_revenue = corporate_revenue - vip_revenue
print('Difference in Average Net Revenue between corporate and vip customers:',round(diff_revenue,2))

#check = df_itc.groupby('Customer_Type')['Room_Rate'].mean()
#check

"""8. Top 10 bookings by Net Revenue - which room types dominate?

Presidential Suite dominates the hotel's ultra-premium inventory, concentrating at 70% of top-10 highest revenue bookings. It confirms that premium inventory is not oversupplied but rather there is a strong-willingness to pay for the top-end products.
"""

top_10_bookings = df_itc.sort_values(by='Net_Revenue',ascending=False).head(10)
print(top_10_bookings[['Booking_ID','Hotel_Name','Hotel_Category','Room_Type','City','Net_Revenue','Booking_Channel','Customer_Type','Customer_Rating']])

print()
top_rooms = top_10_bookings.groupby('Room_Type')['Net_Revenue'].count()
top_rooms.sort_values(ascending=False)

"""9. Payment Mode - which mode should be prioritised?

Credit Card should be priotised while buiding a payment infrastructure.
credit card are staple for corporate and high-quality custumer segment bringing higher highest average net revenue.Therefore ITC should incentivise high-value payment modes through their own co-branded credit card partnerships offering loyalty points, room upgrades, and complimentary services to credit card users.
"""

payment_mode_priority = df_itc.groupby('Payment_Mode')['Net_Revenue'].agg(
    Total_Revenue = 'sum',
    Avg_Revenue = 'mean',
    Count_of_Bookings = 'count'
)
payment_mode_priority.sort_values(by =['Avg_Revenue','Count_of_Bookings'],ascending=[False,False])

"""# **Visualizations**

1. Bar chart - total Net Revenue by Hotel Category.
"""

plt.bar(total_net_revenue.index,total_net_revenue.values,color='blue',edgecolor='black')
plt.xlabel('Hotel Category')
plt.ylabel('Net Revenue Earned(in Billion)')
plt.title('Total Net Revenue Earned by each Hotel Category')
plt.savefig('Net_Revenue_by_Category.png')
plt.show()

"""2. Line chart - total Net Revenue by Month."""

plt.figure(figsize=(9,5))
net_revenue_month= df_itc.groupby('Month')['Net_Revenue'].sum()
plt.plot(net_revenue_month.index,net_revenue_month.values, color='red',marker='o')

plt.xlabel('Month')
plt.ylabel('Net Revenue(in Billion)')
plt.title('Total Net Revenue by Month')

plt.tight_layout()
plt.savefig('Net_Revenue_by_Month.png')
plt.show()

"""3. Histogram - Customer Rating with custom bins."""

custom_bin = [1,2,3,4,4.5,5.0,5.5,6]
plt.hist(df_itc['Customer_Rating'],custom_bin,color='blue', edgecolor='black')
plt.xlabel('Customer_Rating')
plt.ylabel('Total Number Of Customers')
plt.title('Customer Rating Distribution')

plt.savefig('Customer_Rating_Distribution.png')
plt.show

"""4. Two line series - Net Revenue vs Gross Revenue across months."""

plt.figure(figsize=(9,5))

plt.plot(net_revenue_month.index,net_revenue_month.values, color='red',marker='o',label='Net Revenue')
plt.plot(total_gross_revenue.index,total_gross_revenue.values, color='blue',marker='o',label='Gross Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue(in Billion)')
plt.title('Net Revenue vs Gross Revenue across months')
plt.legend()

plt.tight_layout()
plt.savefig('Net_Revenue_vs_Gross_Revenue.png')
plt.show()

"""5. 3-panel vertical dashboard - subplot(3,1,n)."""

plt.figure(figsize=(10, 12))

plt.subplot(3, 1, 1)
revenue_by_city = df_itc.groupby('City')['Net_Revenue'].sum()
plt.bar(revenue_by_city.index,revenue_by_city.values,color='red',edgecolor='black')
plt.xlabel('City')
plt.ylabel('Net Revenue Earned(in Billion)')
plt.grid(True)
plt.title('Total Net Revenue Earned by each City')

plt.subplot(3, 1, 2)
plt.bar(total_net_revenue.index,total_net_revenue.values,color='blue',edgecolor='black')
plt.xlabel('Hotel Category')
plt.ylabel('Net Revenue Earned(in Billion)')
plt.title('Total Net Revenue Earned by each Hotel Category')

plt.subplot(3, 1, 3)
advertisement = df_itc.groupby('Booking_Channel')['Net_Revenue'].count()
plt.plot(advertisement.index,advertisement.values,color='red',marker='o')
plt.xlabel('Booking Channel')
plt.ylabel('Number of Customers')
plt.title('Sale leads by Channel')
plt.grid(True)

plt.tight_layout()
plt.savefig('Dashboard_Vertical.png')
plt.show()

"""6. 3-panel horizontal dashboard - subplot(1,3,n)."""

plt.figure(figsize=(27, 10))

x = df_itc[df_itc['Year'] == 2021].groupby('Quarter')['Net_Revenue'].sum()
y = df_itc[df_itc['Year'] == 2022].groupby('Quarter')['Net_Revenue'].sum()

plt.subplot(1,3,1)
plt.bar(x.index,x.values, color='red')
plt.xlabel('Quarter')
plt.ylabel('Net Revenue(in Billion)')
plt.title('2021 Quarterly Net Revenue')

plt.subplot(1,3,2)
plt.bar(y.index,y.values, color='blue')
plt.xlabel('Quarter')
plt.ylabel('Net Revenue(in Billion)')
plt.title('2022 Quarterly Net Revenue')

plt.subplot(1,3,3)
plt.plot(net_revenue_month.index,net_revenue_month.values, color='red',marker='o',label='Net Revenue')
plt.plot(total_gross_revenue.index,total_gross_revenue.values, color='blue',marker='o',label='Gross Revenue')
plt.xlabel('Month')
plt.ylabel('Revenue(in Billion)')
plt.title('Net Revenue vs Gross Revenue across months')
plt.legend()

plt.tight_layout()
plt.savefig('Dashboard_Horizontal.png')
plt.show()

"""7. 2021 vs 2022 Quarterly Net Revenue - side by side subplots."""

x = df_itc[df_itc['Year'] == 2021].groupby('Quarter')['Net_Revenue'].sum()
y = df_itc[df_itc['Year'] == 2022].groupby('Quarter')['Net_Revenue'].sum()

plt.figure(figsize=(10, 5))
plt.subplot(1,2,1)
plt.bar(x.index,x.values, color='red')
plt.xlabel('Quarter')
plt.ylabel('Net Revenue(in Billion)')
plt.title('2021 Quarterly Net Revenue')

plt.subplot(1,2,2)
plt.bar(y.index,y.values, color='blue')
plt.xlabel('Quarter')
plt.ylabel('Net Revenue(in Billion)')
plt.title('2022 Quarterly Net Revenue')

plt.tight_layout()
plt.savefig('2021_vs_2022_Quarterly_Net_Revenue.png')
plt.show()
